### ISSUE TITLE
TypeError: navigator.storage is undefined

### ISSUE THREAD

**Issue by toddfoster** [phiresky/nmap-log-parse#12]
I've installed in /var/www/nmap on a pi with lighttpd. I access through http://host.local/nmap. I see it successfully find my single log file (just started logging today). But then it hangs:

Brave:
```
Error: TypeError: undefined is not an object (evaluating 'navigator.storage.estimate').
See F12 console for more details.
```
Firefox:
```
Error: TypeError: navigator.storage is undefined.
See F12 console for more details.
```

Safari:
```
Error: TypeError: undefined is not an object (evaluating 'navigator.storage.estimate').
See F12 console for more details.
```

Looks like you're utilizing a function that should be built-in to browsers: I don't understand why this is failing. Any ideas? Thanks.

**Comment by toddfoster** [comment]
[Mozilla's doc's](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorStorage/storage) about NavigatorStorage suggest:
> This feature is available only in secure contexts (HTTPS)

But I'm not sure a proper ssl certificate is possible or even makes sense for a box on my local domain.

Am I barking up the wrong tree?

**Comment by phiresky** [comment]
I think this policy has probably changed in the past (as some other features like Audio which are now only allowed in https), which is why it's used in the code here - and I haven't noticed it because in my case it's served through nginx with a certificate from Let's Encrypt.

Since this is really only used to show a bit of additional info, it should be easily possible to wrap it in a conditional. Try just replacing this:

https://github.com/phiresky/nmap-log-parse/blob/9481485dde3e0899eef68784c77e0c5d1181656b/src/main.tsx#L72

with `const usage = 0;`, see if that fixes it. If so I'll add a fix to the repo.

**Comment by toddfoster** [comment]
That did the trick: thank you!
